//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaptiveDMI.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdaptiveDMI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AdaptiveDMI.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sample Orders.
        /// </summary>
        public static string ListDetailsListDescription {
            get {
                return ResourceManager.GetString("ListDetailsListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ListDetails.
        /// </summary>
        public static string ListDetailsPageTitle {
            get {
                return ResourceManager.GetString("ListDetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings page placeholder text.  Your app description goes here..
        /// </summary>
        public static string SettingsPageAboutText {
            get {
                return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About this application.
        /// </summary>
        public static string SettingsPageAboutTitle {
            get {
                return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose Theme.
        /// </summary>
        public static string SettingsPageChooseThemeText {
            get {
                return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Personalization.
        /// </summary>
        public static string SettingsPagePersonalizationTitle {
            get {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Privacy Statement.
        /// </summary>
        public static string SettingsPagePrivacyStatementText {
            get {
                return ResourceManager.GetString("SettingsPagePrivacyStatementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark.
        /// </summary>
        public static string SettingsPageRadioButtonDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Light.
        /// </summary>
        public static string SettingsPageRadioButtonLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default.
        /// </summary>
        public static string SettingsPageRadioButtonWindowsDefaultTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go back.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _File.
        /// </summary>
        public static string ShellMenuFileHeader {
            get {
                return ResourceManager.GetString("ShellMenuFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Exit.
        /// </summary>
        public static string ShellMenuItemFileExitHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemFileExitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Settings.
        /// </summary>
        public static string ShellMenuItemFileSettingsPageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemFileSettingsPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ListDetails.
        /// </summary>
        public static string ShellMenuItemViewsListDetailsPageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemViewsListDetailsPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main.
        /// </summary>
        public static string ShellMenuItemViewsMainPageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemViewsMainPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main.
        /// </summary>
        public static string ShellMenuItemViewsProcessPageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemViewsProcessPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Views.
        /// </summary>
        public static string ShellMenuViewsHeader {
            get {
                return ResourceManager.GetString("ShellMenuViewsHeader", resourceCulture);
            }
        }
    }
}
